testing the test data set output

diff --git a/.github/workflows/data_drift_model_decay.yml b/.github/workflows/data_drift_model_decay.yml
--- a/.github/workflows/data_drift_model_decay.yml
+++ b/.github/workflows/data_drift_model_decay.yml
@@ -26,82 +26,81 @@ jobs:
         # Add your pipeline commands here
   
   # Job 1: Trigger Airflow DAG
-  trigger-dag:
-    runs-on: ubuntu-latest
+  # trigger-dag:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - name: Install Required Utilities
+  #     run: sudo apt-get update && sudo apt-get install -y curl jq
 
-    steps:
-    - name: Install Required Utilities
-      run: sudo apt-get update && sudo apt-get install -y curl jq
+  #   - name: Generate Unique DAG Run ID
+  #     id: unique_id
+  #     run: echo "::set-output name=dag_run_id::datapipeline_$(date +'%Y%m%d%H%M%S')"
 
-    - name: Generate Unique DAG Run ID
-      id: unique_id
-      run: echo "::set-output name=dag_run_id::datapipeline_$(date +'%Y%m%d%H%M%S')"
+  #   - name: Trigger Airflow DAG
+  #     id: trigger_dag
+  #     env:
+  #       AIRFLOW_USERNAME: admin
+  #       AIRFLOW_PASSWORD: ksmhwqrzhjllqsaz
+  #       AIRFLOW_VM_IP: 34.170.107.190:8080
+  #       AIRFLOW_DAG_ID: datapipeline
+  #     run: |
+  #       echo "Triggering Airflow DAG: $AIRFLOW_DAG_ID with unique DAG Run ID..."
+  #       curl -X POST "http://$AIRFLOW_VM_IP/api/v1/dags/$AIRFLOW_DAG_ID/dagRuns" \
+  #           -H "Content-Type: application/json" \
+  #           -u "$AIRFLOW_USERNAME:$AIRFLOW_PASSWORD" \
+  #           -d "{\"dag_run_id\": \"${{ steps.unique_id.outputs.dag_run_id }}\"}"
 
-    - name: Trigger Airflow DAG
-      id: trigger_dag
-      env:
-        AIRFLOW_USERNAME: admin
-        AIRFLOW_PASSWORD: ksmhwqrzhjllqsaz
-        AIRFLOW_VM_IP: 34.170.107.190:8080
-        AIRFLOW_DAG_ID: datapipeline
-      run: |
-        echo "Triggering Airflow DAG: $AIRFLOW_DAG_ID with unique DAG Run ID..."
-        curl -X POST "http://$AIRFLOW_VM_IP/api/v1/dags/$AIRFLOW_DAG_ID/dagRuns" \
-            -H "Content-Type: application/json" \
-            -u "$AIRFLOW_USERNAME:$AIRFLOW_PASSWORD" \
-            -d "{\"dag_run_id\": \"${{ steps.unique_id.outputs.dag_run_id }}\"}"
+  #   - name: Wait for DAG Completion
+  #     id: wait_for_completion
+  #     env:
+  #       AIRFLOW_USERNAME: admin
+  #       AIRFLOW_PASSWORD: ksmhwqrzhjllqsaz
+  #       AIRFLOW_VM_IP: 34.170.107.190:8080
+  #       AIRFLOW_DAG_ID: datapipeline
+  #       DAG_RUN_ID: ${{ steps.unique_id.outputs.dag_run_id }}
+  #     run: |
+  #       echo "Polling for DAG run status..."
+  #       while true; do
+  #         status=$(curl -s -u "$AIRFLOW_USERNAME:$AIRFLOW_PASSWORD" \
+  #           "http://$AIRFLOW_VM_IP/api/v1/dags/$AIRFLOW_DAG_ID/dagRuns/$DAG_RUN_ID" \
+  #           | jq -r '.state')
 
-    - name: Wait for DAG Completion
-      id: wait_for_completion
-      env:
-        AIRFLOW_USERNAME: admin
-        AIRFLOW_PASSWORD: ksmhwqrzhjllqsaz
-        AIRFLOW_VM_IP: 34.170.107.190:8080
-        AIRFLOW_DAG_ID: datapipeline
-        DAG_RUN_ID: ${{ steps.unique_id.outputs.dag_run_id }}
-      run: |
-        echo "Polling for DAG run status..."
-        while true; do
-          status=$(curl -s -u "$AIRFLOW_USERNAME:$AIRFLOW_PASSWORD" \
-            "http://$AIRFLOW_VM_IP/api/v1/dags/$AIRFLOW_DAG_ID/dagRuns/$DAG_RUN_ID" \
-            | jq -r '.state')
+  #         echo "Current DAG run state: $status"
 
-          echo "Current DAG run state: $status"
+  #         if [ "$status" == "success" ]; then
+  #           echo "DAG run completed successfully!"
+  #           break
+  #         elif [ "$status" == "failed" ]; then
+  #           echo "DAG run failed!"
+  #           exit 1
+  #         else
+  #           echo "DAG is still running. Waiting..."
+  #           sleep 10
+  #         fi
+  #       done
 
-          if [ "$status" == "success" ]; then
-            echo "DAG run completed successfully!"
-            break
-          elif [ "$status" == "failed" ]; then
-            echo "DAG run failed!"
-            exit 1
-          else
-            echo "DAG is still running. Waiting..."
-            sleep 10
-          fi
-        done
+  #   - name: Send Email Notification for DAG Completion
+  #     if: always()
+  #     env:
+  #       SMTP_SERVER: "smtp.gmail.com"
+  #       SMTP_PORT: "587"
+  #       EMAIL_USERNAME: ${{ secrets.SMTP_EMAIL }}
+  #       EMAIL_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
+  #       RECIPIENT_EMAIL: ${{ secrets.TO_EMAIL }}
+  #     run: |
+  #       echo "Airflow DAG email notification"
+  #       (
+  #         echo "Subject: Airflow DAG Status: ${{ job.status }}"
+  #         echo "To: $RECIPIENT_EMAIL"
+  #         echo ""
+  #         echo "Airflow DAG run (ID: ${{ steps.unique_id.outputs.dag_run_id }}) completed with status: ${{ job.status }}."
+  #       ) > email.txt
 
-    - name: Send Email Notification for DAG Completion
-      if: always()
-      env:
-        SMTP_SERVER: "smtp.gmail.com"
-        SMTP_PORT: "587"
-        EMAIL_USERNAME: ${{ secrets.SMTP_EMAIL }}
-        EMAIL_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
-        RECIPIENT_EMAIL: ${{ secrets.TO_EMAIL }}
-      run: |
-        echo "Airflow DAG email notification"
-        (
-          echo "Subject: Airflow DAG Status: ${{ job.status }}"
-          echo "To: $RECIPIENT_EMAIL"
-          echo ""
-          echo "Airflow DAG run (ID: ${{ steps.unique_id.outputs.dag_run_id }}) completed with status: ${{ job.status }}."
-        ) > email.txt
-
-        curl --url "smtp://$SMTP_SERVER:$SMTP_PORT" --ssl-reqd \
-          --mail-from "$EMAIL_USERNAME" \
-          --mail-rcpt "$RECIPIENT_EMAIL" \
-          --upload-file email.txt \
-          --user "$EMAIL_USERNAME:$EMAIL_PASSWORD"
+  #       curl --url "smtp://$SMTP_SERVER:$SMTP_PORT" --ssl-reqd \
+  #         --mail-from "$EMAIL_USERNAME" \
+  #         --mail-rcpt "$RECIPIENT_EMAIL" \
+  #         --upload-file email.txt \
+  #         --user "$EMAIL_USERNAME:$EMAIL_PASSWORD"
 
   # Job 2: Deploy Registry
   deploy-pipeline:
@@ -183,64 +182,64 @@ jobs:
             --upload-file email.txt \
             --user "$EMAIL_USERNAME:$EMAIL_PASSWORD"
 
-  # Job 3: Deploy to Google Cloud Functions
-  deploy-endpoint:
-    runs-on: ubuntu-latest
-    needs: deploy-pipeline
+  # # Job 3: Deploy to Google Cloud Functions
+  # deploy-endpoint:
+  #   runs-on: ubuntu-latest
+  #   needs: deploy-pipeline
 
-    permissions:
-      contents: read
-      id-token: write
+  #   permissions:
+  #     contents: read
+  #     id-token: write
 
-    steps:
-      # Step 1: Checkout Repository
-      - name: Checkout Repository
-        uses: actions/checkout@v3
+  #   steps:
+  #     # Step 1: Checkout Repository
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v3
 
-      # Step 2: Set up Google Cloud SDK
-      - name: Set up Cloud SDK
-        uses: google-github-actions/setup-gcloud@v1
-        with:
-          project_id: ${{ secrets.GCP_PROJECT }}
+  #     # Step 2: Set up Google Cloud SDK
+  #     - name: Set up Cloud SDK
+  #       uses: google-github-actions/setup-gcloud@v1
+  #       with:
+  #         project_id: ${{ secrets.GCP_PROJECT }}
 
-      # Step 3: Authenticate with Google Cloud
-      - name: Authenticate with Google Cloud
-        uses: google-github-actions/auth@v1
-        with:
-          credentials_json: ${{ secrets.GCP_SA_KEY }}
+  #     # Step 3: Authenticate with Google Cloud
+  #     - name: Authenticate with Google Cloud
+  #       uses: google-github-actions/auth@v1
+  #       with:
+  #         credentials_json: ${{ secrets.GCP_SA_KEY }}
 
-      # Step 4: Deploy to Cloud Functions
-      - name: Deploy to Cloud Functions
-        run: |
-          gcloud functions deploy predict-function \
-            --runtime python39 \
-            --trigger-http \
-            --region us-central1 \
-            --entry-point flask_app \
-            --source ./cloud_function \
-            --memory 512MB \
-            --allow-unauthenticated
+  #     # Step 4: Deploy to Cloud Functions
+  #     - name: Deploy to Cloud Functions
+  #       run: |
+  #         gcloud functions deploy predict-function \
+  #           --runtime python39 \
+  #           --trigger-http \
+  #           --region us-central1 \
+  #           --entry-point flask_app \
+  #           --source ./cloud_function \
+  #           --memory 512MB \
+  #           --allow-unauthenticated
 
-      - name: Send Email Notification for Deploy Endpoint
-        if: always()
-        env:
-          SMTP_SERVER: "smtp.gmail.com"
-          SMTP_PORT: "587"
-          EMAIL_USERNAME: ${{ secrets.SMTP_EMAIL }}
-          EMAIL_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
-          RECIPIENT_EMAIL: ${{ secrets.TO_EMAIL }}
-        run: |
-          echo "Deploy endpoint email notification"
-          (
-            echo "Subject: Deploy Endpoint Status: ${{ job.status }}"
-            echo "To: $RECIPIENT_EMAIL"
-            echo ""
-            echo "Deploy Endpoint completed with status: ${{ job.status }}."
-          ) > email.txt
+  #     - name: Send Email Notification for Deploy Endpoint
+  #       if: always()
+  #       env:
+  #         SMTP_SERVER: "smtp.gmail.com"
+  #         SMTP_PORT: "587"
+  #         EMAIL_USERNAME: ${{ secrets.SMTP_EMAIL }}
+  #         EMAIL_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
+  #         RECIPIENT_EMAIL: ${{ secrets.TO_EMAIL }}
+  #       run: |
+  #         echo "Deploy endpoint email notification"
+  #         (
+  #           echo "Subject: Deploy Endpoint Status: ${{ job.status }}"
+  #           echo "To: $RECIPIENT_EMAIL"
+  #           echo ""
+  #           echo "Deploy Endpoint completed with status: ${{ job.status }}."
+  #         ) > email.txt
 
-          curl --url "smtp://$SMTP_SERVER:$SMTP_PORT" --ssl-reqd \
-            --mail-from "$EMAIL_USERNAME" \
-            --mail-rcpt "$RECIPIENT_EMAIL" \
-            --upload-file email.txt \
-            --user "$EMAIL_USERNAME:$EMAIL_PASSWORD"
+  #         curl --url "smtp://$SMTP_SERVER:$SMTP_PORT" --ssl-reqd \
+  #           --mail-from "$EMAIL_USERNAME" \
+  #           --mail-rcpt "$RECIPIENT_EMAIL" \
+  #           --upload-file email.txt \
+  #           --user "$EMAIL_USERNAME:$EMAIL_PASSWORD"
 
